// <auto-generated />
using System;
using Karaoke.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Karaoke.Migrations
{
    [DbContext(typeof(KaraokeContext))]
    [Migration("20191101031312_INIT")]
    partial class INIT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Karaoke.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("OnQueue");

                    b.Property<int?>("SnippetId");

                    b.Property<int?>("SongIdId");

                    b.HasKey("Id");

                    b.HasIndex("SnippetId");

                    b.HasIndex("SongIdId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Karaoke.Entities.SongId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VideoId");

                    b.HasKey("Id");

                    b.ToTable("SongId");
                });

            modelBuilder.Entity("YouTubeKaraoke.Entities.Snippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Channel");

                    b.Property<string>("ChannelId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Snippet");
                });

            modelBuilder.Entity("Karaoke.Entities.Song", b =>
                {
                    b.HasOne("YouTubeKaraoke.Entities.Snippet", "Snippet")
                        .WithMany()
                        .HasForeignKey("SnippetId");

                    b.HasOne("Karaoke.Entities.SongId", "SongId")
                        .WithMany()
                        .HasForeignKey("SongIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
