// <auto-generated />
using System;
using Karaoke.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Karaoke.Migrations
{
    [DbContext(typeof(KaraokeContext))]
    [Migration("20211116021239_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Karaoke.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("OnQueue")
                        .HasColumnType("bit");

                    b.Property<int?>("SnippetId")
                        .HasColumnType("int");

                    b.Property<int?>("SongIdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SnippetId");

                    b.HasIndex("SongIdId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Karaoke.Entities.SongId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VideoId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SongId");
                });

            modelBuilder.Entity("YouTubeKaraoke.Entities.Snippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Snippet");
                });

            modelBuilder.Entity("Karaoke.Entities.Song", b =>
                {
                    b.HasOne("YouTubeKaraoke.Entities.Snippet", "Snippet")
                        .WithMany()
                        .HasForeignKey("SnippetId");

                    b.HasOne("Karaoke.Entities.SongId", "SongId")
                        .WithMany()
                        .HasForeignKey("SongIdId");

                    b.Navigation("Snippet");

                    b.Navigation("SongId");
                });
#pragma warning restore 612, 618
        }
    }
}
